---
- name: Install Caddy
  apt:
    name: caddy
    state: present

- name: Ensure Caddy is enabled
  systemd:
    name: caddy
    enabled: true

- name: Deploy Caddyfile
  copy:
    src: "{{ caddy_config_source }}"
    dest: "{{ caddy_config_dir }}/Caddyfile"
    owner: root
    group: root
    mode: '0644'
  notify: reload caddy
  when: caddy_config_source != ""

- name: Ensure Caddy is started
  systemd:
    name: caddy
    state: started
