---
- name: Install Caddy
  apt:
    name: caddy
    state: present

- name: Ensure Caddy is enabled
  systemd:
    name: caddy
    enabled: true

- name: Check if Caddyfile source exists
  stat:
    path: "{{ playbook_dir }}/../roles/caddy/files/{{ caddy_config_source }}"
  delegate_to: localhost
  register: caddyfile_source
  when: caddy_config_source != ""

- name: Deploy Caddyfile
  copy:
    src: "{{ caddy_config_source }}"
    dest: "{{ caddy_config_dir }}/Caddyfile"
    owner: root
    group: root
    mode: '0644'
  notify: reload caddy
  when: caddy_config_source != "" and caddyfile_source.stat.exists

- name: Ensure Caddy is started
  systemd:
    name: caddy
    state: started
