---
env: stage
private_network: 10.2.0.0/16

timezone: Europe/Berlin

ansible_user: ansible
ansible_user_ssh_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

admin_user: admin
admin_user_ssh_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

firewall_allow_ssh: true
firewall_ssh_port: 22
