---
# REQUIRED: Set your application name
# This will be used for:
#   - System user: {{ app_name }}
#   - Directories: /opt/{{ app_name }}, /var/log/{{ app_name }}, /var/lib/{{ app_name }}, /etc/{{ app_name }}
#   - Systemd services: {{ app_name }}-*
app_name: myapp # ‚Üê CHANGE THIS to your application name

caddy_config_source: stage_Caddyfile

firewall_allow_http: true
firewall_allow_https: true
