---
app_user: "{{ app_name }}"

app_base_dir: "/opt/{{ app_name }}"
app_log_dir: "/var/log/{{ app_name }}"
app_data_dir: "/var/lib/{{ app_name }}"
app_config_dir: "/etc/{{ app_name }}"

deploy_group: deploy
deploy_group_users:
  - "{{ system_user }}"
  - "{{ app_user }}"
