---
postgresql_version: 15
postgresql_listen_addresses: "*"
postgresql_max_connections: 100

postgresql_databases:
  - name: appdb

postgresql_users:
  - name: appuser
    password: "{{ vault_db_password }}"
    database: appdb

firewall_allow_postgresql: true
firewall_postgresql_port: 5432
firewall_postgresql_allowed_networks:
  - "{{ private_network }}"
